Characters grid
pdinarte/web-training pull request #1
Opened 2022-02-16 21:36 UTC by pdinarte

# Pull Request
## Description
A grid for four characters was implemented using HTML and CSS. 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
It was tested  on 2 browsers: Microsoft Edge and Google Chrome.

2022-02-17 16:33 UTC, apadillaAK requested changes
Some changes to apply, also please do the following:
- Center the grid to the page, and add the paddings according to the Figma design
- Change the images to the correct ones.
- Adapt your code to the new images

2022-02-22 16:57 UTC, edamazio-ak requested changes
Great job! Code is ordere, well structured and makes use of the properties requested in the task.

I noticed that you grouped similar CSS properties with an empty line, nice touch!

Complete the requested changes and you'll be good to go! 🚀

2022-02-22 17:41 UTC, apadillaAK approved these changes

2022-02-22 17:43 UTC, edamazio-ak approved these changes
🚀

2022-02-22 18:22 UTC, merged